2gua.rainbow-brackets
ACharLuk.easy-cpp-projects
arthurwang.vsc-prolog
astro-build.astro-vscode
batisteo.vscode-django
boundarystudio.cpp-extentions-pack
bradlc.vscode-tailwindcss
bungcip.better-toml
christian-kohler.npm-intellisense
circledev.glsl-canvas
cschlosser.doxdocgen
danielpinto8zz6.c-cpp-compile-run
DavidAnson.vscode-markdownlint
davidbroetje.algorithm-mnemonics-vscode
dbaeumer.vscode-eslint
denoland.vscode-deno
donjayamanne.githistory
donjayamanne.python-environment-manager
donjayamanne.python-extension-pack
DotJoshJohnson.xml
dpastoor.vscode-nm
dtoplak.vscode-glsllint
dustypomerleau.rust-syntax
EditorConfig.EditorConfig
esbenp.prettier-vscode
felipecaputo.git-project-manager
firefox-devtools.vscode-firefox-debug
formulahendry.auto-rename-tag
foxundermoon.shell-format
franneck94.c-cpp-runner
GeForceLegend.vscode-glsl
GitHub.codespaces
GitHub.copilot-labs
GitHub.copilot-nightly
GitHub.remotehub
GitHub.vscode-pull-request-github
golang.go
GraphQL.vscode-graphql
GraphQL.vscode-graphql-execution
GraphQL.vscode-graphql-syntax
hsnazar.hyper-term-theme
JannisX11.batch-rename-extension
kamikillerto.vscode-colorize
KevinRose.vsc-python-indent
kisstkondoros.vscode-gutter-preview
laurencebahiirwa.deno-std-lib-snippets
LeetCode.vscode-leetcode
LucianIrsigler.nasm
lunarwtr.tga-image-preview
mads-hartmann.bash-ide-vscode
mathe42.surreal-notebook
mathe42.surrealql
Meezilla.json
mgmcdermott.vscode-language-babel
mhutchie.git-graph
miguelsolorio.fluent-icons
moalamri.inline-fold
ms-azuretools.vscode-docker
ms-ossdata.vscode-postgresql
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.anycode-rust
ms-vscode.azure-repos
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.makefile-tools
ms-vscode.remote-explorer
ms-vscode.remote-repositories
ms-vscode.vscode-js-profile-flame
ms-vscode.vscode-typescript-next
mtxr.sqltools
njpwerner.autodocstring
OfHumanBondage.react-proptypes-intellisense
unifiedjs.vscode-mdx
usernamehw.errorlens
vadimcn.vscode-lldb
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
wholroyd.jinja
wix.vscode-import-cost
wk-j.save-and-run
xaver.clang-format
yzhang.markdown-all-in-one
zhuangtongfa.material-theme