formulahendry.auto-rename-tag
GitHub.copilot-nightly
hsnazar.hyper-term-theme
kisstkondoros.vscode-gutter-preview
mhutchie.git-graph
moalamri.inline-fold
ms-vscode-remote.remote-ssh
usernamehw.errorlens
wix.vscode-import-cost